### ISSUE TITLE
能够让istat或者柠檬这些第三方软件显示cpu温度

### ISSUE THREAD

**Issue by qwer130140190** [xiyionxiong/Ryzenintosh#2]
自从SMCAMDProcessor 7.0开始，第三方都不显示温度了
只有使用AMD Power Gadget才能看到温度
之前我都是使用旧版0.6.X
大佬有空看看能否解决这个问题

**Comment by xiyionxiong** [comment]
没有使用三方的显示温度，
我已经升级到 [0.7.1](https://github.com/trulyspinach/SMCAMDProcessor/releases/tag/0.7.1)
你可以自己下载老版本的驱动添加进去
